#ifndef POCKETGAME_TOKEN_H
#define POCKETGAME_TOKEN_H

#include <stddef.h>

typedef enum {
	TOKEN_EOF,
	TOKEN_IDENTIFIER,
	TOKEN_INTEGER,
	TOKEN_STRING,
	TOKEN_LEFT_PAREN,
	TOKEN_RIGHT_PAREN,
	TOKEN_LEFT_BRACE,
	TOKEN_RIGHT_BRACE,
	TOKEN_LEFT_BRACKET,
	TOKEN_RIGHT_BRACKET,
	TOKEN_COMMA,
	TOKEN_SEMICOLON,
	TOKEN_COLON,
	TOKEN_QUESTION,
	TOKEN_DOT,
	TOKEN_PLUS,
	TOKEN_MINUS,
	TOKEN_STAR,
	TOKEN_SLASH,
	TOKEN_PERCENT,
	TOKEN_ASSIGN,
	TOKEN_EQUAL,
	TOKEN_NOT,
	TOKEN_NOT_EQUAL,
	TOKEN_LESS,
	TOKEN_LESS_EQUAL,
	TOKEN_GREATER,
	TOKEN_GREATER_EQUAL,
	TOKEN_AND,
	TOKEN_LOGICAL_AND,
	TOKEN_OR,
	TOKEN_LOGICAL_OR,
	TOKEN_PLUS_ASSIGN,
	TOKEN_MINUS_ASSIGN,
	TOKEN_STAR_ASSIGN,
	TOKEN_SLASH_ASSIGN,
	TOKEN_INCREMENT,
	TOKEN_DECREMENT,
	TOKEN_INVALID
} TokenType;

typedef struct {
	TokenType type;
	const char *start;
	size_t length;
	size_t line;
	size_t column;
} Token;

const char *token_type_name(TokenType type);

#endif